### ISSUE TITLE
So many changed!

### ISSUE THREAD

**Issue by jdongel2004** [spigotpe-beta/Spigotpe#1]
### Issue description

 spigot java...php.... delete... create spigotpe.... I believe this is the last one.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by caspervanneck** [comment]
i know am realy just yea i hate bugs that it have now @jdongel2004  if you wanth to in team you can
